// Dependencies injected into the server factory. Keeping the factory
// host-agnostic (clock, permissions, audit sink, recent source all injected)
// is what makes it unit-testable against a temp dir + in-memory sinks, and
// lets the desktop host later wire in live settings and the trash-routed
// delete without the server package knowing anything about Electron.

import type { PermissionConfig } from "./config.js";
import type { AuditSink } from "./audit/auditLog.js";

export interface PermissionProvider {
  /** Master switch state. */
  isEnabled(): boolean;
  /** Whether a specific tool is currently permitted. */
  isAllowed(tool: string): boolean;
}

export interface RecentFile {
  /** Absolute path on disk. */
  path: string;
  /** Last-modified time (ms), when known. */
  mtimeMs?: number;
}

export interface RecentSource {
  list(limit: number): Promise<RecentFile[]>;
}

/** A workspace root the host has opened, exposed to `list_workspaces`. */
export interface WorkspaceEntry {
  /** Stable id, generated by the host. */
  id: string;
  /** Display name (defaults to the basename of `rootPath`). */
  name: string;
  /**
   * Absolute path to the workspace root. This is the one deliberate
   * absolute-path exposure in the server: a multi-workspace agent needs the
   * real root to pick a workspace to operate in.
   */
  rootPath: string;
}

/** Request passed to a custom delete strategy. */
export interface DeleteRequest {
  absolutePath: string;
  includeAssets: boolean;
  /** Asset folder names the file owns (already discovered by the tool). */
  assetFolderNames: string[];
}

/**
 * One snapshot as the history tools report it. A trimmed projection of the
 * desktop store's record: only the fields an agent needs to choose a snapshot
 * to restore. `source` is "local" or "archive"; `author` is the capture origin
 * (e.g. "user", "agent", "external").
 */
export interface SnapshotSummary {
  id: string;
  ts: number;
  sizeBytes: number;
  author: string;
  agentName?: string;
  source: string;
}

/** One trash entry as `list_trash` reports it (host-side projection). */
export interface TrashEntrySummary {
  trashId: string;
  /** Absolute path the file lived at when deleted (filtered by the tool). */
  originalPath: string;
  deletedAtMs: number;
  expiresAtMs: number | null;
}

/**
 * Optional host capability: snapshot history for a file. Backed by the desktop
 * app's snapshot store, reached over the loopback control bridge. Present only
 * when the spawned server was handed a live bridge descriptor; absent for a
 * standalone `npx @pennivo/mcp-server` run (so the snapshot tools are omitted).
 * Methods THROW on transport failure (app not running / stale descriptor); the
 * tool layer converts that into a clean "app is not running" result.
 */
export interface SnapshotHost {
  list(absPath: string): Promise<SnapshotSummary[]>;
  restore(
    absPath: string,
    snapshotId: string,
    mode: "overwrite" | "as-new-file",
  ): Promise<{ newPath: string } | { error: string }>;
}

/** Optional host capability: the desktop soft-delete trash. Same contract. */
export interface TrashHost {
  list(): Promise<TrashEntrySummary[]>;
  /**
   * Restore a trash entry. `rootPath` is the agent's workspace root; the host
   * enforces it as a boundary BEFORE writing the file back, so an entry from
   * another workspace is rejected without ever being materialized on disk.
   */
  restore(
    trashId: string,
    rootPath: string,
  ): Promise<{ newPath: string } | { error: string }>;
}

export interface ServerDeps {
  /** Absolute workspace root. All tool paths resolve relative to this. */
  root: string;
  /** Permission gate for every tool call. */
  permissions: PermissionProvider;
  /** Where audit events go. */
  audit: AuditSink;
  /** Clock injection (tests pass a fixed clock; CLI/host pass Date.now). */
  now: () => number;
  /** Source for the `pennivo://recent` resource. */
  recent: RecentSource;
  /**
   * Optional custom delete (e.g. the desktop routes deletes through its trash
   * soft-delete). When absent, `delete_file` permanently removes the file (and
   * asset folders when `includeAssets`).
   */
  deleteFile?: (request: DeleteRequest) => Promise<void>;
  /**
   * Optional change subscription (e.g. reuse the desktop folder watcher).
   * Called with a callback to invoke on any workspace change; returns an
   * unsubscribe. When absent, the server watches `root` itself. The factory
   * uses this to emit `notifications/resources/list_changed`.
   */
  subscribeToChanges?: (onChange: () => void) => () => void;
  /**
   * Optional host-provided workspace list (the desktop knows every opened
   * root). When absent, `list_workspaces` synthesizes a single entry from
   * `root` so the standalone single-workspace server still answers the tool.
   */
  workspaces?: () => Promise<WorkspaceEntry[]>;
  /** Id of the active workspace, when the host provides `workspaces`. */
  activeWorkspaceId?: string;
  /**
   * Optional snapshot-history capability (the desktop bridge). When present,
   * `list_snapshots` + `restore_snapshot` are registered; when absent (e.g. the
   * standalone server with no bridge), those tools are omitted entirely.
   */
  snapshots?: SnapshotHost;
  /**
   * Optional trash capability (the desktop bridge). When present, `list_trash`
   * + `restore_from_trash` are registered; when absent, they are omitted.
   */
  trash?: TrashHost;
}

export type { PermissionConfig };
