// Pure data shapes for the multiple-workspaces feature (Phase 1).
//
// A workspace is a named folder root the user has opened in the sidebar.
// Each workspace carries its own per-workspace preferences (last open file,
// sort key, sidebar width, file-open timestamps) so switching roots restores
// the matching view state. These shapes live in @pennivo/core so desktop and
// future hosts agree on the persisted format.

/** One opened folder root, identified by a host-generated stable id. */
export interface Workspace {
  /** Stable id, generated by the host (do not derive from the path). */
  id: string;
  /** Display name, defaults to the basename of `rootPath`. */
  name: string;
  /** Absolute path to the workspace root folder. */
  rootPath: string;
}

/** Per-workspace view preferences, keyed by workspace id in `WorkspacesState`. */
export interface WorkspacePrefs {
  /** Absolute path of the file to reopen on activation, or null for none. */
  lastOpenFile: string | null;
  /** Sidebar sort key (e.g. `name-asc`). Stored as a plain string here. */
  sortKey: string;
  /** Persisted sidebar width in CSS pixels, when the user has resized it. */
  sidebarWidth?: number;
  /** Map of absolute file path to the wall-clock ms it was last opened. */
  fileOpenTimestamps: Record<string, number>;
}

/** Top-level persisted state for all workspaces. */
export interface WorkspacesState {
  /** All opened workspace roots, in user-facing order. */
  workspaces: Workspace[];
  /** Id of the active workspace, or null when none is selected. */
  activeWorkspaceId: string | null;
  /** Per-workspace preferences, keyed by `Workspace.id`. */
  prefs: Record<string, WorkspacePrefs>;
}
